name: mood_tracker
description: "A simple mood tracker app with journaling and insights"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  sqflite: ^2.3.0
  path: ^1.9.0
  intl: ^0.19.0
  table_calendar: ^3.1.2
  fl_chart: ^0.70.0
  provider: ^6.1.2
  
  # Library BARU untuk Foto
  image_picker: ^1.1.2
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true